FROM node:17-alpine
WORKDIR /app

ARG CLIENT_URL
ENV CLIENT_URL=${CLIENT_URL}

ARG STRIPE_SECRET_KEY
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

ARG MONGOSTRING
ENV MONGOSTRING=${MONGOSTRING}

ARG SERVER_URL
ENV SERVER_URL=${SERVER_URL}

COPY ./package.json .
COPY ./package-lock.json .
RUN npm install
COPY . .
EXPOSE 4040
CMD ["node", "server.js"]
